### ISSUE TITLE
TODO: Contract service

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#562]
TODO:

- [ ] Change loading to skeleton
- [ ] Implement refund fee preview
- [ ] Implement refund fee deactivate action
- [ ] Implement refund fee setup update

_Originally posted by @ecbakas in https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/560#issuecomment-2315987492_
