### ISSUE TITLE
General Issue Tracker

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#622]
Collected version of #619 

- [ ] always visible action buttons in forms
- [ ] #652
- [ ] traveller search with query list
- [ ] create contract as edit contract ptf
- [ ] refunt settings,reebate settings,invocing settings,store?(contract create)
- [ ] contract create on CRM pages
- [x] move templates to management > Templates
- [ ] create RebateSettings as query param. (when creating contract u need to create rebate settings)
- [ ] autoform
- [x] navigation implemantation
- [x] Add templates under management
- [x] #653
- [x] Show the left menu
- [ ] Rebate refund scenarios showing (preview)
- [ ] #704
- [ ] Add affiliations to CRM
- [ ] Local storage
- [ ] #705
- [ ] Add sub companies to data grid as sub content
- [x] Unexpected end of json (CRM)
- [x] #672
- [x] Headquarters
- [x] Store
- [x] Merchant
- [ ] Franchise
- [x] Branch code
- [x] Merchant
- [x] Sub merchant
- [ ] Reporter
- [x] #651
- [ ] Filter fetches
- [ ] change all languages in forms and dialogue to match the screen language
- [ ] add filters to all tables
