### ISSUE TITLE
meet tracker 25.09.2024

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#678]
- [x] ◦ Dashboard - Management - Settings
- [ ] ◦ Dashboard as reports (default)
- [ ] #701
- [ ] #702
- [ ] ◦ Multi language put product group 
- [x] ◦ Navbar name cleanup
- [ ] #703
- [x] ◦ Singular navbar text
- [ ] ◦ Traveller List,Add,Edit
- [ ] ◦ Merchant (Organization - Individual)
- [ ] ◦ Merchant oluştururken taxoffice
- [x] ◦ Merchant (edit title )
- [ ] ◦ Merchant indiviudals show hasAccount
- [ ] ◦ Merchant list tags
- [x] ◦ Contract nav
