### ISSUE TITLE
authentication tracker 

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#73]
- [x] https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/54
- [x] https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/69
- [x] #76
- [x] #138
- [x] #98
- [x] Change the client id to .env
- [x] Get scopes from .well-known
- [ ] check authjs adapters
