### ISSUE TITLE
authentication tracker 

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#74]
- [x] https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/54
- [x] https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/69
- [ ] get the user information through the my profile/config API 
- [ ] convert the auth to server side to hide the tokens

**Comment by a0m0rajab** [comment]
Duplicate of https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/73
